dist: xenial
bundler_args: --without debugging documentation
branches:
  only:
    - master
    - "*-stable"

language: ruby
cache: bundler
rvm:
  # The latest ruby version
  - 3.0.0
  - 2.7.0
  - 2.6.2
  - 2.5.0
  - 2.4.2
before_install:
  - gem install bundler -v "~> 1.17"
